% Project Euler - Prob.45
% Triangle, Pentagonal, and Hexagonal numbers are generated by: 
% T = n(n+1)/2 
% P = n(3n-1)/2
% H = n(2n-1)
% Find the next T-P-H number

T=1; P=1; H=1;
% generate all Triangle, Pentag, Hexag numbers up to 100000
for n=2:100000
    T = [T n*(n+1)/2]; 
    P = [P n*(3*n-1)/2];
    H = [H n*(2*n-1)];
end
idx1=[]; idx2=[];
% Find union of Triangle-Pentag numbers --> idx1
for i=1:length(T)
    for j=1:length(P)
        if P(j)==T(i)
            idx1 = [idx1 j];
        end    
    end       
end
% Find union of T-P numbers with Hexag --> idx2   
for k=1:length(H)
   for kk=1:length(idx1)
       if H(k)==P(idx1(kk))
          idx2 = [idx2 k];
          disp('True')
          uint64(H(k))
        end
   end
end
